name: Track File Changes

on:
  push:
    branches:
      - "*"

jobs:
  file-change-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Commit Details
        id: commit_details
        run: |
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Analyze File Changes
        run: |
          git diff --name-status HEAD~1 HEAD > file_changes.txt

      - name: Process File Changes
        run: |
          echo "[" > changes.json
          while read status file; do
            if [ "$status" == "A" ]; then
              ACTION="File Added"
            elif [ "$status" == "M" ]; then
              ACTION="File Updated"
            elif [ "$status" == "D" ]; then
              ACTION="File Deleted"
            fi

            echo "  {" >> changes.json
            echo "    \"filepath\": \"$file\"," >> changes.json
            echo "    \"created_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"," >> changes.json
            echo "    \"created_by\": \"$COMMIT_AUTHOR\"," >> changes.json
            echo "    \"commit_message\": \"$COMMIT_MESSAGE\"," >> changes.json
            echo "    \"action\": \"$ACTION\"" >> changes.json
            echo "  }," >> changes.json
          done < file_changes.txt
          sed -i '$ s/,$//' changes.json # Remove trailing comma from last JSON object
          echo "]" >> changes.json

      - name: Print File Changes
        run: cat changes.json
