name: File Addition Tracker

on:
  push:
    paths:
      - '**'  # Trigger on changes to any files

jobs:
  file-tracking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit details
        id: commit_info
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "commit_author=$(git log -1 --pretty=%an)" >> $GITHUB_ENV
          echo "commit_email=$(git log -1 --pretty=%ae)" >> $GITHUB_ENV
          echo "commit_date=$(git log -1 --pretty=%ad)" >> $GITHUB_ENV

      - name: Find newly added files
        id: find_new_files
        run: |
          git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}' > new_files.txt

      - name: Format file details
        id: format_file_details
        run: |
          repo_name=$(basename -s .git `git config --get remote.origin.url`)
          while IFS= read -r filepath; do
            created_at=$(git log --diff-filter=A --format="%ad" -- $filepath | head -n 1)
            created_by=$(git log --diff-filter=A --format="%an" -- $filepath | head -n 1)
            echo "- File Path: $filepath\n  Created At: $created_at\n  Created By: $created_by\n  Commit Message: $commit_message\n  Status: File Added\n  Repository Name: $repo_name" >> file_details.txt
          done < new_files.txt

      - name: Print file details
        run: |
          echo "File Details:\n"
          cat file_details.txt
