name: List Changed Files

on:
  push:
    branches:
      - main # Adjust to your target branch if not 'main'
  pull_request:
    branches:
      - main

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Get list of changed files
      - name: List Changed Files
        id: changed-files
        run: |
          # Fetch changes based on the event type
          if [ "${{ github.event_name }}" = "push" ]; then
            git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            git diff --name-only origin/${{ github.base_ref }} HEAD
          fi > changed_files.txt
          
          # Print the list of changed files
          echo "Changed files:"
          cat changed_files.txt

      # Display files in GitHub Actions terminal
      - name: Print Changed Files
        run: |
          echo "Relative paths of changed files:"
          cat changed_files.txt
