name: File Change Logger

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  log-file-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - name: Fetch commit details
        id: commit_info
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "COMMIT_HASH: $COMMIT_HASH"
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an' $COMMIT_HASH)
          echo "AUTHOR_NAME: $AUTHOR_NAME"
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' $COMMIT_HASH)
          echo "COMMIT_MESSAGE: $COMMIT_MESSAGE"
          DATE=$(git log -1 --pretty=format:'%ad' --date=iso $COMMIT_HASH)
          echo "DATE: $DATE"

          # Get details for added, modified, and deleted files
          ADDED=$(git diff-tree -r --name-only --no-commit-id --diff-filter=A $COMMIT_HASH | grep -v '/$')
          echo "ADDED: $ADDED"
          MODIFIED=$(git diff-tree -r --name-only --no-commit-id --diff-filter=M $COMMIT_HASH | grep -v '/$'))
          echo "MODIFIED: $MODIFIED"
          DELETED=$(git diff-tree -r --name-only --no-commit-id --diff-filter=D $COMMIT_HASH | grep -v '/$'))
          echo "DELETED: $DELETED"

          # Print the details in a combined format
          echo "Combined File Changes:" > file_changes.log

          for FILE in $ADDED; do
            echo "{\"filepath\": \"$FILE\", \"created_at\": \"$DATE\", \"created_by\": \"$AUTHOR_NAME\", \"commit_message\": \"$COMMIT_MESSAGE\", \"status\": \"File Added\"}" >> file_changes.log
          done

          for FILE in $MODIFIED; do
            echo "{\"filepath\": \"$FILE\", \"created_at\": \"$DATE\", \"created_by\": \"$AUTHOR_NAME\", \"commit_message\": \"$COMMIT_MESSAGE\", \"status\": \"File Updated\"}" >> file_changes.log
          done

          for FILE in $DELETED; do
            echo "{\"filepath\": \"$FILE\", \"created_at\": \"$DATE\", \"created_by\": \"$AUTHOR_NAME\", \"commit_message\": \"$COMMIT_MESSAGE\", \"status\": \"File Deleted\"}" >> file_changes.log
          done

      - name: Print File Changes
        run: |
          cat file_changes.log
