name: List Changed Files

on:
  push:
    branches:
      - main  # Adjust the branch name as per your use case.

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Get list of changed files
      - name: List Changed Files
        run: |
          echo "Files changed in the commit:"
          a = git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | tee changed_files.txt
          echo a

      # Step 3: Display the list of changed files
      - name: Display Changed Files
        run: |
          echo "Changed files:"
          cat changed_files.txt
