name: List Changed Files

on:
  push:
    branches:
      - main  # Adjust the branch name as per your use case.

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Get changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      
