name: List Changed Files

on:
  push:
    branches:
      - main

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the list of changed files
      - name: List changed files
        run: |
          echo "Changed files and their relative paths:"
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
