name: Print File Details on Commit

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch, adjust as needed

jobs:
  print-details:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Get commit details for new files
      run: |
        # Get the list of new files added in the latest commit
        NEW_FILES=$(git diff-tree -r --name-only --no-commit-id --diff-filter=M $COMMIT_HASH | cut -f2-)
        
        # Check if any new files exist
        if [ -n "$NEW_FILES" ]; then
          # Loop through each new file and properly handle spaces
          while IFS= read -r file; do
            # Get the file details
            CREATED_AT=$(git log -1 --format=%ci -- "$file")
            CREATED_BY=$(git log -1 --format=%an -- "$file")
            COMMIT_MESSAGE=$(git log -1 --format=%s -- "$file")
            REPO_NAME=$(basename $(git rev-parse --show-toplevel))

            # Print file details in the specified format
            echo "File: $file"
            echo "Created At: $CREATED_AT"
            echo "Created By: $CREATED_BY"
            echo "Commit Message: $COMMIT_MESSAGE"
            echo "File Added"
            echo "Repository Name: $REPO_NAME"
            echo "----"
          done <<< "$NEW_FILES"
        else
          echo "No new files added in this commit."
        fi
